on:
  push:
    branches:
    - 3.11

jobs:
  mac_arm:
    name: MacOS ARM Build
    runs-on: macos-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/work/Nuitka-Python/Nuitka-Python-Deps
          dep-build
        key: ${{ runner.os }}-arm-${{ hashFiles('build.mac.sh') }}
    - name: Uninstall homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
    - name: Run Build
      run: bash build.mac.sh
    - name: Cleanup artifact
      run: find ~/Library/Nuitka-Python311-arm64 \( -iname '*.o' -o -iname '__pycache__' -o -iname 'link.json' \) | xargs rm -rf
    - uses: actions/upload-artifact@v4
      with:
        name: Nuitka-Python311_mac_arm64
        path: ~/Library/Nuitka-Python311-arm64
  mac_x64:
    name: MacOS Intel Build
    runs-on: macos-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/work/Nuitka-Python/Nuitka-Python-Deps
          dep-build
        key: ${{ runner.os }}-intel-${{ hashFiles('build.mac.sh') }}
    - name: Uninstall homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
    - name: Run Build
      run: arch -x86_64 bash build.mac.sh
    - name: Cleanup artifact
      run: find ~/Library/Nuitka-Python311-x86_64 \( -iname '*.o' -o -iname '__pycache__' -o -iname 'link.json' \) | xargs rm -rf
    - uses: actions/upload-artifact@v4
      with:
        name: Nuitka-Python311_mac_x86_64
        path: ~/Library/Nuitka-Python311-x86_64

  windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - name: Run Build
      shell: cmd
      run: build.bat
    - name: Cleanup rebuild interpreters
      run: Get-ChildItem -Path $(Get-Location) -File -Include *.old_interp -Recurse | Remove-Item -Force -Verbose
    - uses: actions/upload-artifact@v4
      with:
        name: Nuitka-Python311_windows_x64
        path: output
